# .gitpod.yml
image:
  file: .gitpod.Dockerfile

tasks:
  - init: mvn clean install -DskipTests
    command: mvn test

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - vscjava.vscode-maven
    - ritwickdey.LiveServer

ports:
  - port: 6080
    onOpen: ignore